services:
  - type: web
    name: cybvars-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cybvars-db
          property: connectionString
databases:
  - name: cybvars-db
